# Generated by Django 4.0.1 on 2022-01-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
