# Generated by Django 4.0.1 on 2022-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0002_icecream_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ice_cream_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='icecream',
            name='type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
