# Generated by Django 4.0.1 on 2022-01-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0003_icecreamtype_icecream_type_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IceCreamType',
        ),
    ]
