# Generated by Django 4.0.1 on 2022-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0004_delete_icecreamtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ice_cream_shops',
                'managed': True,
            },
        ),
    ]
